
fastlane_version "1.110.0"

default_platform :ios

platform :ios do
  before_all do
  end

  desc "Default CI lane"
  lane :ci do
    lint
    test
    coverage
  end

  desc "Runs all the tests"
  lane :test do
    pod_lib_lint
    scan(
      device: "iPhone XS"
    )
  end

  desc "Slather sends code coverage to Coveralls"
  lane :coverage do
    slather(
      proj: "GTZoomableImageView.xcodeproj",
      scheme: "GTZoomableImageView-iOS",
      ignore: "Tests/*",
      coveralls: true
    )
  end

  lane :lint do
    swiftlint(
      mode: :lint,
      config_file: ".swiftlint.yml",
      ignore_exit_status: false
    )
  end

  desc "Clean environment after all operations"
  lane :clean do
    clean_build_artifacts
  end

  after_all do |lane|
    clean_build_artifacts
  end

  error do |lane, exception|
  end
end
